config/routes.rb
Rails.application.routes.draw do
  # get 'static_pages/home'
  get 'about', to: 'static_pages#about'
  get 'projects', to: 'static_pages#projects'
  get 'contact', to: 'static_pages#contact'
  get 'resume', to: 'static_pages#resume'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root 'static_pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @currentTime = Time.now
    @formatted_currentTime = @currentTime.strftime("%H:%M %d/%m/%Y")
  end

  def about
  end

  def projects
  end

  def contact
  end

  def resume
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PersonalWebsite</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css2?family=Lora:ital,wght@0,400;0,700;1,400;1,700&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <%# <body style="background-color: grey;"> %>
  <body>
    <%# render navbar partial %>
    <%= render 'navbar' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<div class="navbar">
  <button>
    <%= link_to "About", about_path %>
  </button>
  <button>
    <%= link_to "Projects", projects_path %>
  </button>
  <button>
    <%= link_to "Contact", contact_path %>
  </button>
</div>

app/views/static_pages/_navbar.html.erb
<div id="menu">
  <div id="menu-items">
    <%= link_to 'Home', root_path, class: 'menu-item' %>
    <%= link_to 'About', about_path, class: 'menu-item' %>
    <%= link_to 'Projects', projects_path, class: 'menu-item' %>
    <%= link_to 'Contact', contact_path, class: 'menu-item' %>
    <%= link_to 'Resume', resume_path, class: 'menu-item' %>
  </div>
  <div id="menu-background-pattern"></div>
</div>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/home.html.erb
<div class="container">
  <%= @formatted_currentTime %>
</div>

app/views/static_pages/projects.html.erb
<h1>StaticPages#projects</h1>
<p>Find me in app/views/static_pages/projects.html.erb</p>

app/views/static_pages/resume.html.erb
<h1>Resume page</h1>